apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genai-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: genai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /rewrite
            pathType: Prefix
            backend:
              service:
                name: nginx-gateway
                port:
                  number: 8080
          - path: /summarize
            pathType: Prefix
            backend:
              service:
                name: nginx-gateway
                port:
                  number: 8080
          - path: /email
            pathType: Prefix
            backend:
              service:
                name: nginx-gateway
                port:
                  number: 8080
