apiVersion: v1
kind: Service
metadata:
  name: summarize-service
  labels:
    app: summarize
spec:
  selector:
    app: summarize
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
